spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  datasource:
    url: jdbc:postgresql://localhost:5432/proxy_rest_service
    username: postgres
    password: password
  jpa:
    show-sql: true

users:
  url: https://jsonplaceholder.typicode.com/users
posts:
  url: https://jsonplaceholder.typicode.com/posts
albums:
  url: https://jsonplaceholder.typicode.com/albums

setup:
  roles-and-privileges: false

cache:
  life-time-in-minutes: 5
  max-size: 100
