spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vk-test
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

users:
  url: https://jsonplaceholder.typicode.com/users
posts:
  url: https://jsonplaceholder.typicode.com/posts
albums:
  url: https://jsonplaceholder.typicode.com/albums

setup:
  roles-and-privileges: false
  test-users: false
